server:
  port: 9003

spring:
  # spring boot升级至2.1.x时默认禁用bean覆盖，需要配置启用
  main:
    allow-bean-definition-overriding: true
  application:
    name: mplus-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

turbine:
  appConfig: mplus-common, mplus-hystrix
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  # combine-host: true
  # instanceUrlSuffix:
    # default: actuator/hystrix.stream

