server:
  port: 9002
spring:
  application:
    name: mplus-system #应用名称
  # spring boot升级至2.1.x时默认禁用bean覆盖，需要配置启用
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
